### ISSUE TITLE
No puedo resolver la dependencia de DipucrIntegra

### ISSUE THREAD

**Issue by FranAlcon96** [ctt-gob-es/SIGM#12]
¿ Alguien sabe como o dónde puedo obtener el jar ? 

Failed to execute goal on project sigem_autenticacion: Could not resolve dependencies for project es.ieci.tecdoc.sigem:sigem_autenticacion:jar:3.0.1-M2: Could not find artifact es.gob.afirma:DipucrIntegra:jar:1.2.2_002 in repo_arch (file:/home/franjalcon/repos/SIGM-Community-SIGM4.0-QUIJOTE/sigem/SIGEM_Autenticacion/lib)

Saludos.

**Comment by agustinjm** [comment]
Buenos días Fran, el código está en https://github.com/ctt-gob-es/SIGM-Community/tree/SIGM4.0-QUIJOTE/modulos/dipucrintegra

Ejecuta el comando siguiente a nivel de la carpeta .../dipucrintegra para que te genere el jar en la carpeta target

call mvn clean install -Dmaven.test.skip=true

Cuando pueda actualizo el pom.xml que hay a nivel de la carpeta modulos para que compile la librería

Saludos

**Comment by FranAlcon96** [comment]
Resuelto, muchas gracias.
