### ISSUE TITLE
Compilación SIGM 5: error  InfoDistribution

### ISSUE THREAD

**Issue by moalmi1** [ctt-gob-es/SIGM#14]
Hola,

Al intentar compilar SIGM 5 me encuentro un error en SIGEM_RegistroPresencialModules/SIGEM_RegistroPresencial:

SIGM-Community-SIGM5.0-QUIJOTE\sigem\SIGEM_RegistroPresencial_Modul
es\SIGEM_RegistroPresencial\src\main\java\ieci\tecdoc\sgm\registropresencial\uti
ls\SigemRegistroServiceAdapterUtil.java:[443,34] cannot find symbol
symbol  : method getComentarios()
location: class ieci.tecdoc.sgm.registropresencial.info.InfoDistribution

Al ir a ver la clase InfoDistribution en registro/ISicres-Server (que además hay una copia de la clase en el raíz del proyecto que no debería estar ahí) veo que no hay nada de ese método (ni nada sobre comentarios).

¿Quizás no está bien subido ese proyecto?

Gracias!

Miguel A. Molinero

**Comment by mqelvira** [comment]
Hola Miguel.

No me había dado cuenta de la clase esa en el raiz, la he quitado, pero no debería afectar.
He mirado la clase InfoDistribución de ieci.tecdoc.sgm.registropresencial.info y sí tiene el parámetro comentarios y sus métodos de acceso.
Puedes indicarme en qué paso de la compilación te falla, porque he visto que esas dos clases se compilan en la segunda llamada (la del -Djars) y en principio compila los proyectos en el orden correcto.
En el log del maven me sale que compila los proyectos:
...
[INFO] ISicres-Server
[INFO] sigem_rde
[INFO] SIGEM_ConsolidacionConfigLoader
[INFO] ISicres-Desktop-Jar
[INFO] ISicres-Document-Connector-Invesdoc
[INFO] ISicres-PersonManager
[INFO] ISicres-Document-Connector-Alfresco
[INFO] ISicres-resources-configurable
[INFO] ISicres-Document-Connector
[INFO] fwktd-sir-parent
[INFO] fwktd-sir-core
[INFO] fwktd-sir-wsclient
[INFO] fwktd-dm
[INFO] fwktd-dm-core
[INFO] fwktd-dm-bd
[INFO] fwktd-dm-invesdoc
[INFO] fwktd-dm-alfresco
[INFO] fwktd-dm-service
[INFO] fwktd-sir-api
[INFO] ISicres-Api
[INFO] sigem_registroPresencial_modules
[INFO] sigem_registroPresencial-configurable-resources
[INFO] sigem_entidades
[INFO] sigem_registroPresencial
...

**Comment by moalmi1** [comment]
Hola Manuel,

Tienes razón, sí que está. Creo que es problema mío que no estaba compilando la rama correcta :( Disulpa!

**Comment by moalmi1** [comment]
Hola,

En el ISicres-Server sí que tengo la correcta ya y el orden de los proyectos parece el correcto (es en -Djars donde me falla), pero esa misma clase está en RegistroPresencial y ahí no están los comentarios:

 SIGM-Community/sigem/SIGEM_RegistroPresencial_Modules/SIGEM_RegistroPresencial/src/main/java/ieci/tecdoc/sgm/registropresencial/info/InfoDistribution.java 

Parece que la dependencia es con esta última clase y ahí es donde no encuentra el método.

**Comment by mqelvira** [comment]
Efectivamente no debe estar ahí.
He revisado nuestros commits y esa clase y otras 4 más se movieron para la integración con el registro MSSSI y al mover el código ha añadido las nuevas pero las viejas no las ha quitado.
Las clases movidas son:
  - registro/
    - ISicres-Server/
      - src/main/java/
        - ieci/tecdoc/sgm/registropresencial/
          - autenticacion/User.java
          - distribution/ConsultDistribution.java
          - info/InfoDistribution.java
          - utils/Keys.java
          - utils/RBUtil.java

Las he quitado de su ubicación vieja.
Ya me comentas si sigue y cómo lo hace y disculpad los problemas.

**Comment by moalmi1** [comment]
Arreglado! Y no te preocupes. Al contrario, gracias por reponder tan rápido.
