### ISSUE TITLE
Compilación SIGM 5: Error postgres.properties en MSSSI

### ISSUE THREAD

**Issue by moalmi1** [ctt-gob-es/SIGM#15]
Hola,

Me encuentro con que al compilar (-Djars) el proyecto framework-dir3-MSSSI\dir3-api, intenta buscar un archivo de properties en el el RegistroPresencialMSSSIWeb (que en teoría se compila más tarde). Ese archivo no lo encuentra (ni siquiera existe la carpeta database en el github):

[INFO] ------------------------------------------------------------------------
[INFO] Building dir3-api
[INFO]    task-segment: [clean, install]
[INFO] ------------------------------------------------------------------------
[INFO] [clean:clean {execution: default-clean}]
[INFO] [resources:resources {execution: default-resources}]
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. b
uild is platform dependent!
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error loading property file 'F:\traspasos\SIGM-Community-SIGM5.0-QUIJOTE\
SIGM-Community\framework-dir3-MSSSI\dir3-api\..\..\sigem\SIGEM_RegistroPresencia
lMSSSI_Modules\SIGEM_RegistroPresencialMSSSIWeb\src\main\filters\database\Postgr
es.properties'

Gracias!

**Comment by mqelvira** [comment]
Hola.
He estado mirando y solo veo un par de cosas que pueden ser.
  - ¿Qué versión de maven utilizas? La salida del log es distinta que la que me devuelve a mi.
Nosotros actualizamos a apache-maven-3.2.2, las hay más nuevas pero no funciona (aún jeje).
  - En la ruta se come las dos \ que debe tener entre dir3-api y \sigem, ahí debe ser \..\..
Si esa es la ruta exacta que busca (y no lo ha truncado el log) es posible que sea eso, pero no sé por qué te las quita. ¿Has probado con -X o -e (no me acuerdo bien) para que pinte el log completo?

Ya me comentas.

**Comment by moalmi1** [comment]
Hola Manuel,

Efectivamente estoy en Maven 2, aunque no creo que sea el problema en este caso concreto.

Sobre la ruta, en la que he pegado se ha comido las dos barras, pero en el de verdad sí están. En todo caso, como comentaba, si sigues la ruta en la que busca ese archivo, no está. Ni siquiera existe la carpeta database en el repositorio. He supuesto que es por eso por lo que da el error.

Voy a probar con Maven 3 a ver que pasa por si acaso.

**Comment by moalmi1** [comment]
Confirmado, con maven 3.2.2 mismo error

**Comment by mqelvira** [comment]
jaja, espera, he visto que tenía en el .gitignore *database* por lo que estaba ignorando esa carpeta y alguna otra. 
Subo:
  - .gitignore
  - sigem/
    - SIGEM_RegistroPresencialMSSSI_Modules/
      - SIGEM_RegistroPresencialMSSSIJAXWS/sigm.webservices/
        - src/main/resources/SIGEM_RegistroPresencial/
          - database.properties
      - SIGEM_RegistroPresencialMSSSIWeb/src/main/filters/database/
        - DB2.properties
        - Oracle.properties
        - Postgres.properties
        - SqlServer.properties
    - SIGM/src/main/resources/reponfs/config/
      - SIGEM_Core/database.properties
      - SIGEM_RegistroPresencial/database.properties

Al final dejamos esto fino.

**Comment by moalmi1** [comment]
Jejejeje Gracias! Esa es la idea, voy poniendo lo que encuentre y vamos refinando el release.
