### ISSUE TITLE
Problema compilando SIGM para bajar dependencias tras quitar soporte protocolos TLSv1 GitHub

### ISSUE THREAD

**Issue by ROG-H** [ctt-gob-es/SIGM#16]
A principios de 2018 GitHub quitó el soporte a los protocolos de conexión TLSv1/TLSv1.1 (https://github.blog/2018-02-23-weak-cryptographic-standards-removed/) lo que hace que desde entonces al tratar de compilar SIGM que está en Java 6 (que en principio no soporta TLSv1.2) no pueda bajar las dependencias de los repisotorios maven, por ejemplo nada más empezar: 
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:2.5 from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version

Consultaros por favor como estáis resolviendo o como creéis pueda ser la mejor solución para este problema:
- Crear un proyecto con todas las librerias necesarias que haría de maven repository que cualquier desarrollador podría incluir para poder compilar y donde se añadirían las nuevas librerias necesarias.
- Migrar a Java 8 y tratar de solucionar los problemas derivados de pasar Java 8 (si es que todos son solucionables) hasta hacer de nuevo que compile.
- Activar TLSv1.2 con Java 1.6 (update 111 or later) updates que hay que conseguir a través del soporte de Oracle al estar solo disponible hasta la jdk6u45
- ...

**Comment by mqelvira** [comment]
Hola.
La intención que tenemos es ir migrando poco a poco todos los proyectos a java 8 (o el que toque), pero mientras estamos limitados a no actualizar maven más allá de la versión 3.2.2 (probamos alguna posterior y fallaba, pero no sé si hay intermedias que sí funcione) y a gestionar varias versiones de java.

En concreto yo tengo configurado en el settings.xml de maven :
				<JAVA_1_4_HOME>C:/Program Files/Java/jdk1.6.0_18</JAVA_1_4_HOME>
				<JAVA_1_5_HOME>C:/Program Files/Java/jdk1.6.0_18</JAVA_1_5_HOME>
				<JAVA_1_6_HOME>C:/Program Files/Java/jdk1.7.0_25</JAVA_1_6_HOME>
				<JAVA_1_7_HOME>C:/Program Files/Java/jdk1.7.0_25</JAVA_1_7_HOME>
				<JAVA_1_8_HOME>C:/Program Files/Java/jdk1.8.0_45</JAVA_1_8_HOME>

Los proyectos están configurados para que cada uno utilice el java que necesite, y por defecto en la variable JAVA_HOME del equipo tengo C:/Program Files/Java/jdk1.7.0_25 para que use este por defecto.
Con esto en principio ya no daba ese error, porque sí que nos dio en algunos proyectos y lo que hicimos fue cambiarle la versión de java con la que compilaba (creo que eso fue todo).

No sé si te ayuda esto, ya nos comentas.

**Comment by spanishkangaroo** [comment]
@mqelvira buenas, ayudaría mucho si estas "configuraciones" estuvieran en una página del proyecto en lugar de en los comentarios. ¿Podríais hacerlo?

**Comment by mqelvira** [comment]
Hola @spanishkangaroo.
Todas la configuración inicial y primera compilación está subida en el documento:
https://github.com/ctt-gob-es/SIGM-Community/blob/SIGM5.0-QUIJOTE/README.txt

Quizás sí que sería interesante ir montando una wiki o algo así, no sé si es eso a lo que te refieres. Pero quizás cuando ya esté la versión estable, no sé, lo que decida la comunidad.

Saludos.

**Comment by ROG-H** [comment]
Muchas gracias @mqelvira , Solucionado!

Contactamos con la gente de Sistemas y tenemos usuario de soporte de Oracle. Nos bajaron la jdk6u211 y con esa se compila todo sin problemas. soporta TLSv1.2 y accede sin problemas a los repositorios remotos y baja todas las dependencias!

Así que de momento si se quiere seguir con la jdk6 es una opción usar los updates u111 y posteriores, pero sólo son accesibles con usuarios de soporte de Oracle. (el último update público de la jdk6 de Oracle es la jdk6u45 que soporta los protocolos TLS v1 obsoletos).

Y si se quiere ir ya migrando de jdk de Java a superiores, la otra es seguir la solución que me indicabas que también he aplicado en cuanto a la configuración de los Java en el settings de maven.

**Comment by alfonso-ava** [comment]
Hola,

Aunque llego tarde, por si sirve comento la configuración con la que he conseguido compilar:


                <JAVA_1_5_HOME>/etc/java/jdk1.6.0_45</JAVA_1_5_HOME>
                <JAVA_1_6_HOME>/usr/local/java/jdk1.8.0_201</JAVA_1_6_HOME>
                <JAVA_1_7_HOME>/usr/local/java/jdk1.8.0_201</JAVA_1_7_HOME>
		<JAVA_1_8_HOME>/usr/local/java/jdk1.8.0_201</JAVA_1_8_HOME>

[alfonso@localhost utils]$ mvn -version
Apache Maven 3.5.4 (Red Hat 3.5.4-4)
Maven home: /usr/share/maven
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: /usr/local/java/jdk1.8.0_201/jre
Default locale: es_ES, platform encoding: UTF-8
OS name: "linux", version: "5.0.7-200.fc29.x86_64", arch: "amd64", family: "unix"

**Comment by ROG-H** [comment]
Muchas gracias a todos, cierro el issue
