### ISSUE TITLE
Quijote5: Falta incluir el fichero sigm.ear en el proyecto

### ISSUE THREAD

**Issue by jmbob** [ctt-gob-es/SIGM#18]
Hola.

En la UPNA hemos terminado de compilar el proyecto sin ningún problema, pero en el módulo SIGEM_RegistroPresencialMSSSIJAXWS es necesario el fichero sigm.ear y no está incluido.
En el pom.xml se incluye en la siguientes líneas:
	
	<modules>
		<module>sigm.webservices</module>
		<module>sigm.dao</module>
		**<module>sigm.ear</module>**
	</modules>

Supongo que será algún problemilla al subir el módulo con el .gitignore.

Muchas gracias y un saludo.

**Comment by mqelvira** [comment]
Sastamente. Se quita la exclusión *.ear del .gitignore y se añade el proyecto sigm.ear.
A ver si no falta nada más :)

**Comment by jmbob** [comment]
Mucha gracias!
