### ISSUE TITLE
Compilación SIGM5: Error al generar configuración

### ISSUE THREAD

**Issue by joseagudomontero** [ctt-gob-es/SIGM#22]
Buenos días:

Al generar la distribución de SIGEM ya con la cofiguración y todo. Me da un error

```
[ERROR]   The project es.msssi.tecdoc.sigem:SIGEM_RegistroPresencialMSSSI_Modules:3.0.0-msssi2.0.0  fuentes\sigem\SIGEM_RegistroPresencialMSSSI_Modules\pom.xml) has 1 error
[ERROR]   Child module  fuentes\sigem\SIGEM_RegistroPresencialMSSSI_Modules\SIGEM_RegistroPresencialMSSSIWeb-resources-configurable of  sigem\SIGEM_RegistroPresencialMSSSI_Modules\pom.xml does not exist
```
Para solucionarlo, en el fichero 

`fuentes\sigem\SIGEM_RegistroPresencialMSSSI_Modules\pom.xml`

Hay que cambiar:

```
<modules>
<!-- jagudo: <module>SIGEM_RegistroPresencialMSSSIWeb-resources-configurable</module> -->
<module>SIGEM_RegistroPresencialMSSSIWeb-configurable-resources</module>
</modules>
```
La linea comentada como "jagudo" es la que da el error y la segunda es la correcta ya que hace referencia a un módulo que no existe.

Si voy encontrado mas problemas los iré posteando junto a la solución.

**Comment by mqelvira** [comment]
Hola José.

Perdona por haber tardado tanto en contestar.
Ya he incluido la corrección al código de la rama SIGEM5.0-Quijote.

Gracias.
Un saludo.
