### ISSUE TITLE
Error al buscar tercero tras realizar registro telemático

### ISSUE THREAD

**Issue by AleDH** [ctt-gob-es/SIGM#25]
Buenos días, a ver si me podéis mirar esto. Llevo toda la mañana probando a modificar ficheros de configuración, pero no doy con la tecla.
```
ERROR invesicres.thirdparty.SicresThirdPartyAPI - Error en la búsqueda de terceros
ieci.tdw.ispac.api.errors.ISPACException: javax.naming.NameNotFoundException: El nombre jdbc no este asociado a este contexto
        at ieci.tdw.ispac.ispaclib.db.DbCnt.getConnection(DbCnt.java:157)
        at ieci.tdw.ispac.ispaclib.invesicres.thirdparty.SicresThirdPartyAPI.lookup(SicresThirdPartyAPI.java:105)
        at ieci.tdw.ispac.api.BasicThirdPartyAPI.lookup(BasicThirdPartyAPI.java:17)
        at ieci.tecdoc.sgm.terceros.SigemTercerosServiceAdapter.lookup(SigemTercerosServiceAdapter.java:71)
        at ieci.tecdoc.sgm.registro.action.IniciarExpedienteAction.insertarDefaultMailTercero(IniciarExpedienteAction.java:543)
        at ieci.tecdoc.sgm.registro.action.IniciarExpedienteAction.executeAction(IniciarExpedienteAction.java:448)
        at ieci.tecdoc.sgm.registro.action.RegistroWebAction.execute(RegistroWebAction.java:50)
        at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
        at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
        at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
```

**Comment by joseagudomontero** [comment]
Buenas Ale.

Da la impresion de que no tienes bien configurada el tomcat de eclipse,
prueba a ver. lo siguiente:

En la configuración del Tomcat debes tener (en mi caso la
conf es para Oracle y la IP pon  te corresponda como servidor de BDD.)

Si estas operando con eclipse hazlo en la configración de tomcat que te
aprece en eclipse en el arbol de proyectos.

ten en cuenta que en el registro telemático no hay una entidad definida y deberia cogerte la 000 

Mira especialmente si tienes las entradas CON <<name="jdbc/registroDS">> sin el "_000" tanto el server.xml como en el context.xml

SERVER.XML

   <Resource auth="Container" driverClassName="oracle.jdbc.OracleDriver"
logAbandoned="true" maxActive="20" maxIdle="10" maxWait="-1"
name="jdbc/sigemAdmin" password="****" removeAbandoned="true"
removeAbandonedTimeout="5" type="javax.sql.DataSource"
url="jdbc:oracle:thin:@192.168.1.1:1521:aph" username="SIGEMADMIN"/>

<Resource auth="Container" driverClassName="oracle.jdbc.OracleDriver"
logAbandoned="true" maxActive="20" maxIdle="10" maxWait="-1"
name="jdbc/eTramitacionDS_000" password="*******" removeAbandoned="true"
removeAbandonedTimeout="5" type="javax.sql.DataSource"
url="jdbc:oracle:thin:@192.168.1.1:1521:aph" username="ETRAMITACION_000"/>
<Resource auth="Container" driverClassName="oracle.jdbc.OracleDriver"
logAbandoned="true" maxActive="20" maxIdle="10" maxWait="-1"
name="jdbc/registroDS_000" password="*****" removeAbandoned="true"
removeAbandonedTimeout="5" type="javax.sql.DataSource"
url="jdbc:oracle:thin:@192.168.1.1:1521:aph" username="REGISTRO_000"/>

<Resource auth="Container" driverClassName="oracle.jdbc.OracleDriver"
logAbandoned="true" maxActive="20" maxIdle="10" maxWait="-1"
name="jdbc/tramitadorDS_000" password="*****" removeAbandoned="true"
removeAbandonedTimeout="5" type="javax.sql.DataSource"
url="jdbc:oracle:thin:@192.168.1.1:1521:aph" username="TRAMITADOR_000"/>

<Resource auth="Container" driverClassName="oracle.jdbc.OracleDriver"
logAbandoned="true" maxActive="20" maxIdle="10" maxWait="-1"
name="jdbc/archivoDS_000" password="*****" removeAbandoned="true"
removeAbandonedTimeout="5" type="javax.sql.DataSource"
url="jdbc:oracle:thin:@192.168.1.1:1521:aph" username="ARCHIVO_000"/>

<Resource auth="Container" driverClassName="oracle.jdbc.OracleDriver"
logAbandoned="true" maxActive="20" maxIdle="10" maxWait="-1"
name="jdbc/tercerosDS_000" password="******" removeAbandoned="true"
removeAbandonedTimeout="5" type="javax.sql.DataSource"
url="jdbc:oracle:thin:@192.168.1.1:1521:aph" username="REGISTRO_000"/>

<Resource auth="Container" driverClassName="oracle.jdbc.OracleDriver"
logAbandoned="true" maxActive="20" maxIdle="10" maxWait="-1"
name="jdbc/fwktd-sirDS_000" password="*********" removeAbandoned="true"
removeAbandonedTimeout="5" type="javax.sql.DataSource"
url="jdbc:oracle:thin:@192.168.1.1:1521:aph" username="FWKTD_SIR_000"/>

<Resource auth="Container" driverClassName="oracle.jdbc.OracleDriver"
logAbandoned="true" maxActive="20" maxIdle="10" maxWait="-1"
name="jdbc/fwktd-auditDS_000" password="************"
removeAbandoned="true" removeAbandonedTimeout="5"
type="javax.sql.DataSource" url="jdbc:oracle:thin:@192.168.1.1:1521:aph"
username="FWKTD_AUDIT_000"/>

<Resource auth="Container" driverClassName="oracle.jdbc.OracleDriver"
logAbandoned="true" maxActive="20" maxIdle="10" maxWait="-1"
name="jdbc/fwktd-dir3DS" password="***************" removeAbandoned="true"
removeAbandonedTimeout="5" type="javax.sql.DataSource"
url="jdbc:oracle:thin:@192.168.1.1:1521:aph" username="FWKTD_DIR3"/>

<Resource auth="Container" driverClassName="oracle.jdbc.OracleDriver"
logAbandoned="true" maxActive="20" maxIdle="10" maxWait="-1"
name="jdbc/fwktd-sirDS" password="*******************"
removeAbandoned="true" removeAbandonedTimeout="5"
type="javax.sql.DataSource" url="jdbc:oracle:thin:@192.168.1.1:1521:aph"
username="FWKTD_SIR_000"/>

<Resource auth="Container" driverClassName="oracle.jdbc.OracleDriver"
logAbandoned="true" maxActive="20" maxIdle="10" maxWait="-1"
name="jdbc/registroDS" password="*******************"
removeAbandoned="true" removeAbandonedTimeout="5"
type="javax.sql.DataSource" url="jdbc:oracle:thin:@192.168.1.1:1521:aph"
username="REGISTRO_000"/>

Y en el fichero context.xml (e mi caso son estos)


<Context>

    
    <WatchedResource>WEB-INF/web.xml</WatchedResource>

    
    

    
    

    

<ResourceLink global="jdbc/registroDS_000" name="jdbc/registroDS_000"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/fwktd-dir3DS" name="jdbc/fwktd-dir3DS"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/fwktd-sirDS_000" name="jdbc/fwktd-sirDS_000"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/sigemAdmin" name="jdbc/sigemAdmin"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/fwktd-auditDS_000" name="jdbc/fwktd-auditDS_000"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/registroDS" name="jdbc/registroDS"
type="javax.sql.DataSource"/>



<ResourceLink global="jdbc/registroDS_000" name="jdbc/registroDS_000"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/fwktd-dir3DS" name="jdbc/fwktd-dir3DS"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/fwktd-sirDS_000" name="jdbc/fwktd-sirDS_000"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/fwktd-auditDS_000" name="jdbc/fwktd-auditDS_000"
type="javax.sql.DataSource"/>



<ResourceLink global="jdbc/sigemAdmin" name="jdbc/sigemAdmin"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/eTramitacionDS_000"
name="jdbc/eTramitacionDS_000" type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/registroDS_000" name="jdbc/registroDS_000"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/tramitadorDS_000" name="jdbc/tramitadorDS_000"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/tercerosDS_000" name="jdbc/tercerosDS_000"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/fwktd-auditDS_000" name="jdbc/fwktd-auditDS_000"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/fwktd-sirDS_000" name="jdbc/fwktd-sirDS_000"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/fwktd-dir3DS" name="jdbc/fwktd-dir3DS"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/archivoDS_000" name="jdbc/archivoDS_000"
type="javax.sql.DataSource"/>



<ResourceLink global="jdbc/registroDS_000" name="jdbc/registroDS_000"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/tramitadorDS_000" name="jdbc/tramitadorDS_000"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/fwktd-auditDS_000" name="jdbc/fwktd-auditDS_000"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/archivoDS_000" name="jdbc/archivoDS_000"
type="javax.sql.DataSource"/>



<ResourceLink global="jdbc/sigemAdmin" name="jdbc/sigemAdmin"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/registroDS_000" name="jdbc/registroDS_000"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/fwktd-auditDS_000" name="jdbc/fwktd-auditDS_000"
type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/oracle_interWs8Ws9"
name="jdbc/oracle_interWs8Ws9" type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/fwktd-sirDS" name="jdbc/fwktd-sirDS"
type="javax.sql.DataSource"/>

</Context>

**Comment by AleDH** [comment]
Si, por ahí iban los tiros. Al final era que me faltaba añadir

`<ResourceLink global="jdbc/tercerosDS_000" name="jdbc/tercerosDS_000" type="javax.sql.DataSource"/>
` 
al context SIGEM_RegistroTelematicoWeb. 

Creía que ya lo había probado antes, pero me equivocaría y seguramente se lo añadí a otro context. 

Gracias por la ayuda

**Comment by SantiagoCr8** [comment]
Context ctxa = new InitialContext();
//
Context ctx = (Context)ctxa.lookup("java:comp/env");

DataSource ds = (DataSource) ctx.lookup("jdbc/nombre");

verificar si tienes bien las 3 lineas de codigo
