### ISSUE TITLE
No encuentro plantilla de documento 'Documentos Sellados'

### ISSUE THREAD

**Issue by AleDH** [ctt-gob-es/SIGM#29]
Buenas tardes.

Entre los scripts de actualización de bd hay uno en tramitador que se llama '05-insertDocumentosSellados.sql' que inserta valores en las tablas spac_ct_tpdoc y spac_p_plantdoc.

Pero no encuentro el correspondiente script de la tabla spac_p_blp para esa plantilla, que es donde se guardan los binarios de las plantillas.

Gracias

**Comment by mqelvira** [comment]
Hola.
Realmente es una plantilla en blanco ya que no se usa. Ese tipo de documento se usa para generar el PDF con todos los documentos registrados, sellados y concatenados para imprimir de una sola vez. Pero aún así, añado al script la plantilla por si diera algún error por no estar.
