### ISSUE TITLE
Integración con Alfresco 5 mediante CMIS

### ISSUE THREAD

**Issue by jesusrv** [ctt-gob-es/SIGM#3]
Buenos días,

En Universidad Politécnica de Cartagena tenemos una instalación "tuneada" de SIGM 3.0.1, integrada con un Alfresco 4.2.1. 

En los próximos meses vamos a migrar a **Alfresco 5**. El problema es que a partir de esta versión **DESAPARECEN los Web Services SOAP** que utiliza el conector actual de SIGM (ISicres-Document-Connector-Alfresco), con lo que no nos dejaría de funcionar el almacenamiento y lectura de ficheros. La alternativa que propone Alfresco es utilizar acceso por CMIS en lugar de por WS.

¿Alguno de vosotros tiene implementada (o lo ha intentado al menos) esta adaptación del conector a **Alfresco CMIS**? No tenemos experiencia con el protocolo CMIS y, viendo el código fuente del conector actual, la adaptación no parece que vaya a ser sencilla.

Gracias y un saludo.

**Comment by aesteban-msssi** [comment]
Hola Jesús:

Nosotros (Ministerio de Sanidad) tenemos previsto realizar esa adaptación a lo largo de 2017. Quizá podamos mantenernos al tanto de los avances que vayamos realizando.

Un saludo,

Alfredo

**Comment by jesusrv** [comment]
Jajaja creo que no vamos a tener tanto tiempo, la implantación de Alfresco 5 aquí es bastante inmiente. Os informaré de los avances cuando nos podamos meter en faena.

Un saludo.

**Comment by aesteban-msssi** [comment]
Sería estupendo que compartierais los cambios vía un Pull Request para que podamos integrarlos o al menos acceder a ellos.

**Comment by jesusrv** [comment]
Claro, avisaremos cuando tengamos una solución para poder compartirla con la comunidad.

**Comment by jmbob** [comment]
Hola.

En el commit UPNA-003 de SIGM-QUITOTE V5 hemos creado un nuevo conector para Alfresco 5 a partir del código que nos dejó la Univerdad Politécnica de Cartagena que implementaron para SIGEM V3.

Hay información adicional en la carpeta documentacion del proyecto.
