### ISSUE TITLE
Error en SIGEM_EstructuraWeb: Falta campo email en tabla IUSERGROUPHDR

### ISSUE THREAD

**Issue by jmbob** [ctt-gob-es/SIGM#32]
Modificar usuarios y/o dar de alta nuevos grupos en el estructura de SIGEM no funcionaba correctamente porque faltaba añadir el campo email en la tabla IUSERGROUPHDR.

Hemos dado de alta el campo con el tamaño que para los usuarios.
ALTER TABLE IUSERGROUPHDR ADD (EMAIL VARCHAR2(256 CHAR) );

Manu, si me pasas la instrucción para PostgreSQL subo todo en un mismo commit.

Un saludo.

**Comment by mqelvira** [comment]
Buenas.

En PostgreSQL sería:
ALTER TABLE IUSERGROUPHDR ADD COLUMN EMAIL VARCHAR(300);

Saludos.

**Comment by jmbob** [comment]
Muchas gracias!

Ya están subidos los cambios en el commit UPNA-014.

Saludos.
