### ISSUE TITLE
Error al compilar versión SIGM5.0-QUIJOTE

### ISSUE THREAD

**Issue by ideasenespanol** [ctt-gob-es/SIGM#85]
He bajado la ultima versión el día de hoy para retomar nuevamente el proyecto, he seguido las instrucciones del Readme.txt, pero me he encontrado con los siguientes errores:

1. He tenido que usar jdk 1.8 para poder compilar ya que las versiones anteriores hay errores con el SSL de https://repo1.maven.org/maven2/
2. Hay una libreria de db2 3.50.152 que ya no existe (me imagino que debe ser que no se usa ya db2)
3. No termina de compilar, siempre quedo en el modulo 
[INFO] Modulo con clases para acceso a LDAP ............... FAILURE [  1.498 s]
El error que genera es:
[ERROR] C:\ALSIGM\SIGM\framework\fwktd-ldap\src\main\java\es\ieci\tecdoc\fwktd\ldap\core\connector\impl\LdapConnectorSpringImpl.java:[62,11] error: cannot access InitializingBean

Si ha alguno le ha pasado este error y me puede orientar se lo agradeceria.

**Comment by ROG-H** [comment]
Buenas,

Revisa esta issue cerrada: https://github.com/ctt-gob-es/SIGM-Community/issues/16

Que entiendo está relacionada a ver si responde todas tus cuestiones.

Por un lado hay jars como el de db2 que creo que están ahora en la carpeta lib y hay que poner en el pom para cogerlos del repositorio local de esa carpeta lib o copiarlos en el proyecto/lib y que los coja de ahí.

Y por otro para el tema de los errores son SSL, otra opción para compilar con jdks 6 o 7 pero usando las versiones que oracle advanced o support https://www.oracle.com/java/technologies/javase/6-relnotes.html como la jdk6u211 por ejemplo, que para descargarlas es posible que sea necesario tener usuario de soporte o algo de Oracle.

A ver si con todo esto consigues compilarlo de nuevo.

**Comment by ideasenespanol** [comment]
Hola, realice los cambios indicados, funciona bajandome librerias, pero, llego al mismo punto de falla

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on projec
t fwktd-ldap: Compilation failure
[ERROR] /GIT/SIGM-Community/framework/fwktd-ldap/src/main/java/es/ieci/tecdoc/fwktd/ldap/core/connector
/impl/LdapConnectorSpringImpl.java:[62,26] cannot access org.springframework.beans.factory.InitializingBean
[ERROR]   class file for org.springframework.beans.factory.InitializingBean not found

Lo raro es que al mirar esa clase en la linea indicada no se hace referencia org.springframework.beans.factory.InitializingBean

Voy a seguir revisando, pero si alguno se le ocurre algo por favor me cuentan

Mi objetivo es dejar una maquina en GCP o AWS para quien a futuro desee trabajar solo sea clonarla.

**Comment by ROG-H** [comment]
Hola de nuevo, he intentado reproducir tu error. he prescindido del repository de artefactos que ya tengo y tratado de compilar el proyecto completo como si sería la primera vez.
Te adelanto la siguientes configuración que tengo en el settings.xml en la carpeta .m2:
<?xml version="1.0" encoding="UTF-8"?>
<settings>
  <profiles>
    <profile>
      <id>development</id>
      <properties>
      	<JAVA_1_4_HOME>D:\Programas\Java\jdk1.6.0_211</JAVA_1_4_HOME>
		<JAVA_1_5_HOME>D:\Programas\Java\jdk1.6.0_211</JAVA_1_5_HOME>
		<JAVA_1_6_HOME>D:\Programas\Java\jdk1.6.0_211</JAVA_1_6_HOME>
		<JAVA_1_7_HOME>D:\Programas\Java\jdk1.7.0_221</JAVA_1_7_HOME>
		<JAVA_1_8_HOME>D:\Programas\Java\jdk1.8.0_191</JAVA_1_8_HOME>
      </properties>
    </profile>
  </profiles>
  <activeProfiles>
    <activeProfile>development</activeProfile>
  </activeProfiles>
</settings>

Y sigo el punto 2 de compilación del README.txt:
2.- Compilación del código:
    Una vez descargado se realiza la primera compilación necesaria para que se generen los 
artefactos necesarios tanto para desplegar directamente la aplicación como para que compile 
el código y se puedan realizar desarrollos.
    En la primera compilación hay que ejecutar los siguientes comandos en el orden indicado desde 
la ruta donde se hay descagado el código (por ejemplo C:\ALSIGM\alsigm):

    mvn clean install -Dmaven.test.skip=true -Dinit
    mvn clean install -Dmaven.test.skip=true -Djars
    mvn clean install -Dmaven.test.skip=true
    mvn clean install -Dmaven.test.skip=true -Dwars
    mvn clean install -Dmaven.test.skip=true -Dears -P generate-distri

- El -Dinit sin problemas success.
- El primer error me da haciendo el -Djars con invesdoc-core que modifico el pom.xml y sólo dejo en repositories el local que mira en /lib y quito el otro ya que ya no está disponible la libreria fplibrary.
- Termina -Djars success y el resto -Dwars, -Dears .. todos success y sin problemas.

A ver si esto te ayuda.

**Comment by ROG-H** [comment]
Hola de nuevo, he intentado reproducir tu error. he prescindido del 
repository de artefactos que ya tengo y tratado de compilar el proyecto 
completo como si sería la primera vez.
Te adelanto la siguientes configuración que tengo en el settings.xml en 
la carpeta .m2:

<?xml version="1.0" encoding="UTF-8"?>
<settings>
   <profiles>
     <profile>
       <id>development</id>
       <properties>
<JAVA_1_4_HOME>D:\Programas\Java\jdk1.6.0_211</JAVA_1_4_HOME>
<JAVA_1_5_HOME>D:\Programas\Java\jdk1.6.0_211</JAVA_1_5_HOME>
<JAVA_1_6_HOME>D:\Programas\Java\jdk1.6.0_211</JAVA_1_6_HOME>
<JAVA_1_7_HOME>D:\Programas\Java\jdk1.7.0_221</JAVA_1_7_HOME>
<JAVA_1_8_HOME>D:\Programas\Java\jdk1.8.0_191</JAVA_1_8_HOME>
       </properties>
     </profile>
   </profiles>
   <activeProfiles>
     <activeProfile>development</activeProfile>
   </activeProfiles>
</settings>

Y sigo el punto 2 de compilación del README.txt:
2.- Compilación del código:
Una vez descargado se realiza la primera compilación necesaria para que 
se generen los
artefactos necesarios tanto para desplegar directamente la aplicación 
como para que compile
el código y se puedan realizar desarrollos.
En la primera compilación hay que ejecutar los siguientes comandos en el 
orden indicado desde
la ruta donde se hay descagado el código (por ejemplo C:\ALSIGM\alsigm):

|mvn clean install -Dmaven.test.skip=true -Dinit mvn clean install 
-Dmaven.test.skip=true -Djars mvn clean install -Dmaven.test.skip=true 
mvn clean install -Dmaven.test.skip=true -Dwars mvn clean install 
-Dmaven.test.skip=true -Dears -P generate-distri |

  * El -Dinit sin problemas success.
  * El primer error me da haciendo el -Djars con invesdoc-core que
    modifico el pom.xml y sólo dejo en repositories el local que mira en
    /lib y quito el otro ya que ya no está disponible la libreria fplibrary.
  * Termina -Djars success y el resto -Dwars, -Dears .. todos success y
    sin problemas.

A ver si esto te ayuda.

**Comment by ideasenespanol** [comment]
Hola, tengo una duda, he buscado las versiones que indicas de Java para sistemas Linux y Windows y no estan disponibles, adicionalmente queria preguntarte que version de java usas para la ejecución del Maven

Gracias

**Comment by ROG-H** [comment]
Hola de nuevo,

Esas versiones de Java normalmente hay que descargarlas con contrato de 
soporte de Oracle, en nuestro caso nos la bajaron la gente de sistemas, 
consulta si en tu organización tenéis soporte de Oracle porque en ese 
caso tendréis acceso con la cuenta de Oracle para descargar esas jdk.

En cuanto a la versión de java que uso para la ejecución de Maven es la 
siguiente:

Java version: 1.6.0_211, vendor: Sun Microsystems Inc.
Java home: D:\Programas\Java\jdk1.6.0_211\jre

que es la que tengo en la variable de entorno de JAVA_HOME: 
D:\Programas\Java\jdk1.6.0_211

Un Saludo,

**Comment by ideasenespanol** [comment]
Hola, he logrado realizar la compilación de los componentes base, sigo documentando el proceso seguido y lo dejare publicado acá por si alguien lo necesitara a futuro, he usado los JDK que están públicos en la pagina de Oracle

**Comment by ideasenespanol** [comment]
El procedimiento seguido para la compilación del proyecto ha sido.
1. Tener el Java 1.6, 1.7 y 1.8 (ultimas versiones)
2. Maven 3.2.2 y 3.6.3
3. Hacer un mvn install con java 1.8 y  maven 3.2.2 y luego con maven 3.6.3 con el pom.xml que adjunto dentro del zip, esto bajara la mayor cantidad de librerías que se necesitan para compilar el proyecto
4. Después copiar las librerias que están en la carpeta lib a la carpeta repository, sobreescribira algunas.
5. He usado el .bat que adjunto y he empezado la compilación con Java1.7 y maven 3.2.2, cuando ha generado errores de librerias, he cambiado la compilación para usar Java 1.8 y maven 3.6.3 (para la compilación con java1.7 he agregado la opción -o a la compilación para que trabaje offline)
6. Cuando de problemas de compilación con Java 1.8, hay que usar Java 1.7 de esta manera se evitara las validaciones que hace Java 1.8 de las dependencias.

Espero les sirva a quien desee compilar y construir el proyecto con JDK disponibles sin suscripción.

[descargalibs.zip](https://github.com/ctt-gob-es/SIGM-Community/files/4931384/descargalibs.zip)
